name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-act-js
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: cp -vuR web/* /var/cache/hosting/plaintext.casa/
